### ISSUE TITLE
Just curious... how has it performed for you?

### ISSUE THREAD

**Issue by ghost** [pirate/crypto-trader#3]

**Comment by ghost** [comment]
I spent a few hours working on something similar to this and was curious to see if anyone has had any luck with something like this. Its a simple enough concept, and a good algorithm could work well, but I wonder how well it will work given that coinbase doesn't have very quick transfers... usually it takes a couple days before the coin is yours to sell.

**Comment by pirate** [comment]
I wrote this years ago when transactions were fast and almost free, I'm surprised it keeps getting traffic.  The algorithm specified in the README doesn't work, you can prove it to yourself with this script: 

https://gist.github.com/pirate/eac582480aa34b5adda9e6adc1878190
